model_name = "ddqn_v0.1.0.pth"

[architecture]
input_size = 100
num_layers = 3
layer_sizes = [147, 256, 128, 49]
output_size = 10

[hyperparameters]
learning_rate = 0.0005
gamma = 0.99
epsilon_start = 1.0
epsilon_end = 0.01
epsilon_decay = 0.995
target_update_freq = 500
memory_capacity = 50000
batch_size = 1
tau = 0.1


[training]
num_episodes = 15000
save_interval = 500
invalid_action_limit = 5
