model_name = "pg_v0.2.0.pth"

[architecture]
layer_sizes = [147, 256, 128, 49]

[hyperparameters]
learning_rate = 0.0001
gamma = 0.99
max_step = 100

[training]
num_episodes = 5000

[reward_function]
hit = 0.1
sunk = 0.1
miss = -0.1
other = -0.5
done = 0.1