[model]
model_name = "sea2_dqn_v0.2.0"
type = "dqn"

[architecture]
board_width = 6
board_length = 6
input_size = 108
hidden_size = [189, 128]
output_size = 36

[hyperparameters]
learning_rate = 0.0001
gamma = 0.98
eps_start = 1.0
eps_decay = 0.9968
eps_min = 0.01
buffer_size = 18000
batch_size = 512
invalid_action_limit = 8

[reward_function]
no_hit = -0.05
ship_hit = 0.05
free_hit = 0.1
ship_sunk = 0.05
free_ship_sunk = 0.1
invalid_guess = -1
game_over = 0.1

[training]
num_episodes = 53000
