[model]
model_name = "sea2_dqn_v0.1.0.pth"
type = "dqn"

[architecture]
board_width = 6
board_length = 6
input_size = 108
hidden_size = [256, 64]
output_size = 36

[hyperparameters]
learning_rate = 0.0001
gamma = 0.99
eps_start = 1.0
eps_decay = 0.996
eps_min = 0.01
buffer_size = 20000
batch_size = 64
invalid_action_limit = 10

[reward_function]
no_hit = -0.1
ship_hit = 0.1
free_hit = 0.3
ship_sunk = 0.2
free_ship_sunk = 0.4
invalid_guess = -1
game_over = 1

[training]
num_episodes = 5000
