[model]
model_name = "sea2_pg_v0.1.0.pth"
type = "PolicyGradient"
save_path = "models/"

[architecture]
layer_sizes = [147, 345, 128, 49]

[hyperparameters]
learning_rate = 0.0001
gamma = 1
max_step = 500

[training]
num_episodes = 6000

[reward_function]
no_hit = 0.1
ship_hit = -0.1
free_hit = -0.5
ship_sunk = -0.1
free_ship_sunk = -0.5
invalid_guess = 5.0
game_over = -0.1