[model]
model_name = "sea2_dqn_v0.1.0.pth"
type = "dqn"

[architecture]
input_size = 147
hidden_size = [512, 128]
output_size = 49

[hyperparameters]
learning_rate = 0.0001
gamma = 0.99
epsilon_start = 1.0
epsilon_decay = 0.995
epsilon_min = 0.01
buffer_size = 20000
batch_size = 512
max_step = 300

[reward_function]
no_hit = -0.1
ship_hit = 0.1
free_hit = 0.3
ship_sunk = 0.2
free_ship_sunk = 0.4
invalid_guess = -1
game_over = 1

[training]
num_episodes = 5000
